"""

Revision ID: 25ee1ae9e5d7
Revises: 
Create Date: 2024-12-16 07:58:16.713676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ee1ae9e5d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_unique', sa.Boolean(), nullable=True))
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.drop_column('is_unique')
        batch_op.drop_column('visitor_id')

    # ### end Alembic commands ###
