"""change enrollment reqs to json

Revision ID: 3fa0152c944f
Revises: 25ee1ae9e5d7
Create Date: 2025-03-03 16:00:43.551663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa0152c944f'
down_revision = '25ee1ae9e5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.drop_column('visitor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
